---
title: "STT810 ICA1 Tiancheng Liu"
date: "2022-09-06"
output:
  word_document:
    toc: yes
    toc_depth: '3'
  html_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
    theme: united
    highlight: tango
    css: my.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

### a
```{r}
sample(1:50,10)

```

### b

```{r}
sample(1:50,10,replace = TRUE)
```

### c

```{r}
(1+50)/2
mean_sample <- mean(sample(1:50,100000,replace = TRUE))
mean_sample
#As the results showed above, I believe the are similar
```


### d

```{r}
res1 <- sample(c(0,1),100,replace = TRUE, prob = c(2/3,1/3))
res1
```



### e
```{r}
res2 <- sample(c(0,0,1),100, replace = TRUE)

res2
```


## Question 2

### a

```{r}
runif(10,0,5)
```

### b

```{r}
u <- runif(10000,0,5)
hist(u)
```

Yes it is uniform


### c

```{r}
hist(u^2)
```

No the histogram is not uniform.

## Question 3

### a

```{r}
(43+68)/68
```


### b

```{r}
(43+68)/43
```

### c

#### I
The probability of both A and B if they are independent is 0.4*0.6 = 0.24.

#### II
The minimum probability is 0, when A and B have no overlapping.

#### III
The maximum probability is 0.4, when B is containing every element of A.



