---
title: "STT810 ICA3 Tiancheng Liu"
author: "Tiancheng Liu"
date: "2022-09-13"
output:
  word_document:
    toc: yes
    toc_depth: '3'
  html_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
    theme: united
    highlight: tango
    css: my.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## a

```{r}
sim <- 10000
win <- replicate(sim,0)
for(i in 1:sim){
  P <- c(0,0,0)
  while(max(P) < 8){
    for(j in 1:3){
      roll <- sample(1:6,1)
      P[j] = P[j] + roll
      if(P[j] >= 8){
        break
      }
    }
  }
  win[i] <- j
}
sum(win == 1)/sim
sum(win == 2)/sim
sum(win == 3)/sim
```


## b

```{r}
sim <- 10000
win <- replicate(sim,0)
for(i in 1:sim){
  P <- c(0,0,0)
  while(max(P) < 50){
    for(j in 1:3){
      roll <- sample(1:6,1)
      P[j] = P[j] + roll
      if(P[j] >= 50){
        break
      }
    }
  }
  win[i] <- j
}
sum(win == 1)/sim
sum(win == 2)/sim
sum(win == 3)/sim
```

The winning percentage for 1 lowers and the winning percentage ofr 2 and 3 increases, since it takes more rolls to stack to 50, 2 and 3 have more chances to roll larger numbers than 1.

## c

```{r}
sim <- 10000
win <- replicate(sim,0)
for(i in 1:sim){
  P <- c(0,0,0)
  while(max(P) < 50){
    for(j in 1:3){
      roll <- sample(1:4,1)
      P[j] = P[j] + roll
      if(P[j] >= 50){
        break
      }
    }
  }
  win[i] <- j
}
sum(win == 1)/sim
sum(win == 2)/sim
sum(win == 3)/sim
```

The winning percentage is similar to that in b. Because the chances for them to roll a side of the dice are still the same, the earlier the dice the higher of chance they have to win.

## d

```{r}
sim <- 10000
win <- replicate(sim,0)
for(i in 1:sim){
  P <- c(0,0,0)
  while(max(P) < 8){
    for(j in 1:3){
      roll <- sample(1:6,1)
      P[j] = P[j] + roll
      if(P[j] == 4){
      roll <- sample(1:6,1)
      P[j] = P[j] + roll
    }
      if(P[j] >= 8){
        break
      }
    }
  }
  win[i] <- j
}
sum(win == 1)/sim
sum(win == 2)/sim
sum(win == 3)/sim
```

## e

```{r}
sim <- 10000
win <- replicate(sim,0)
for(i in 1:sim){
  P <- c(0,0,0,0,0)
  while(max(P) < 8){
    for(j in 1:5){
      roll <- sample(1:6,1)
      P[j] = P[j] + roll
      if(P[j] == 4){
      roll <- sample(1:6,1)
      P[j] = P[j] + roll
    }
      if(P[j] >= 8){
        break
      }
    }
  }
  win[i] <- j
}
sum(win == 1)/sim
sum(win == 2)/sim
sum(win == 3)/sim
sum(win == 4)/sim
sum(win == 5)/sim
hist(win)
```

