---
title: "ICA7"
author: "Tiancheng Liu"
date: "2022-09-27"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

### a

∫(0,4) 1/8*x^2

1/24x^3|(0,4) = 64/24-0 = 8/3

### b

varance = E(X^2) – (E(X))^2

(E(X))^2 = 64/9

E(X^2) = ∫(0,4) 1/8*x^3 = 1/32x^4|(0,4) = 8

varance = E(X^2) – (E(X))^2 = 8 - 64/9 = 8/9


## Question 2

### a

```{r}
E <- 1*0.1 + 2*0.2 + 3*0.1 + 4*0.1 + 5*0.1 + 6*0.2 + 7*0.1 + 8*0.1

E

EX <- 1^2*0.1 + 2^2*0.2 + 3^2*0.1 + 4^2*0.1 + 5^2*0.1 + 6^2*0.2 + 7^2*0.1 + 8^2*0.1

var <- EX - E^2

var
```

The expected value is 4.4, variance is 5.04.

## Question 3

### b

```{r}
mean(rpois(1000,8))
```


## Question 4

### a

```{r}
mean(rbinom(1000000,24,0.3))

var(rbinom(1000000,24,0.3))
```

Expected value is 7.2, variance is 5.03.


### b

```{r}
mean(rbinom(1000000,150,0.8))

var(rbinom(1000000,150,0.8))
```

Expected value is 120, variance is 23.99.


### d

```{r}
mean(rexp(1000000,0.3))

var(rexp(1000000,0.3))
```

Expected value is 3.33 and variance is 11.11.

### e

```{r}
mean(rexp(1000000,3))

var(rexp(1000000,3))
```

Expected value is 0.33 and variance is 0.11.
### f

```{r}
mean(rnorm(1000000,4,1.4))

var(rnorm(1000000,4,1.4))
```

Expected value is 3.99 and variance is 1.96.