---
title: "ICA11"
date: "2022-10-11"
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
  word_document:
    toc: yes
    toc_depth: '3'
  html_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
    theme: united
    highlight: tango
    css: my.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

### a

````{r}
exp1 <- rexp(1000000,1/3)
exp2 <- rexp(1000000,1/3)

sum12 <- exp1 + exp2

ex1 <- mean(exp1)
ex2 <- mean(exp2)
ex_sum12 <- mean(sum12)
ex_sum12
ex1 + ex2


```
We can see they are the same.

### b

```{r}
var1 <- var(exp1)
var2 <- var(exp2)
varsum <- var(sum12)

var1+var2
varsum
```

We can see they are the same.


## Question 2

### a


```{r}
library(MASS)
var_x <- 1.5
var_y <- 1.5
cor_xy <- -0.8
Sigma <- cbind(c(var_x,cor_xy*sqrt(var_x)*sqrt(var_y)),c(cor_xy*sqrt(var_x)*sqrt(var_y),var_y))
sim <- MASS::mvrnorm(n = 1000000, mu = c(0,0), Sigma)
x <- sim[,1]
y <- sim[,2]
z <-  x+y
cov(x,y)
```
We can see it is close to -1.2.

### b

```{r}
mean(z)
mean(x) + mean(y)
```

They are the same.

### c

```{r}
var(x) + var(y) + 2*cov(x,y)
var(z)
```

They are the same.

## Question 3

### a

```{r}

total <- rep(0,20000)
for (i in 1:20000){
  sim <- rexp(10000,1/3)
  total[i] <- mean(sim)
}

hist(total)
```


Yes, the histogram is just like a normal distribution.

